---
driver:
  name: vagrant
  vagrantfile_erb: test/integration/Vagrantfile.erb
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536
      addl_volumes: 2

suites:
  - name: local
    run_list:
      - recipe[storage::default]
    attributes:
