---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: aws_dev
  ssh_key: <%= ENV['HOME'] %>/.ssh/aws_dev.pem
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      image_id: ami-6f969506
      flavor_id: c3.xlarge
  # - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[storage::ec2test]
      - recipe[storage::default]
    attributes:
