---
driver:
  name: ec2
  subnet_id: subnet-a792da8f
  iam_profile_name: test-ebs-attachment
  tags:
    Env: test
    Type: test
    Operator: <%= ENV['USER'] %>

provisioner:
  name: chef_zero
  attributes:
    storage:
      ebs_volumes:
        vol1:
          device: /dev/xvde
          size: 2
          delete_on_termination: true

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[storage::default]
  - name: ubuntu-18.04
    run_list:
      - recipe[storage::default]

suites:
  - name: ebs
    driver:
      tags:
        Name: storage-ebs-test
      instance_type: t2.medium
  - name: es
    driver:
      tags:
        Name: storage-es-test
      instance_type: c3.xlarge
  - name: nvme
    driver:
      tags:
        Name: storage-nvme-test
      instance_type: i3.large
