---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: aws_dev
  ssh_key: <%= ENV['HOME'] %>/.ssh/aws_dev.pem
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  flavor_id: c3.xlarge
  require_chef_omnibus: true
  username: ubuntu

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret

platforms:
- name: ubuntu-12.04
  driver:
    image_id: ami-e002a788
    tags:
      Name: vagrant-default-ubuntu-1204
      Env: public

suites:
  - name: ec2
    run_list:
      - recipe[storage::ec2test]
      - recipe[storage::default]
    attributes:
