---
driver:
  name: ec2
  require_chef_omnibus: 12.10.24
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.xlarge
  interface: public
  iam_profile_name: test-ebs-attachment
  tags:
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04

suites:
  - name: ec2
    driver:
      tags:
        Name: storage-ec2-ubuntu-1404
    run_list:
      - recipe[aws::ec2_hints]
      - recipe[storage::default]
    attributes:
      storage:
        ebs_volumes:
          vol1:
            device: /dev/xvde
            size: 2
            delete_on_termination: true
