---
driver:
  name: ec2
  subnet_id: subnet-f1f6acac  # development-public-us-east-1b
  # TODO: Switch to the below when
  #       https://github.com/test-kitchen/kitchen-ec2/issues/394 is fixed
  # subnet_filter:
  #   tag: 'Name'
  #   value: 'development-public-us-east-1b'
  iam_profile_name: test-ebs-attachment
  tags:
    Env: test
    Type: test
    Operator: <%= ENV['USER'] %>

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  attributes:
    storage:
      ebs_volumes:
        vol1:
          device: /dev/xvde
          size: 2
          delete_on_termination: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[storage::default]
  - name: ubuntu-18.04
    run_list:
      - recipe[storage::default]

suites:
  - name: ebs
    driver:
      tags:
        Name: storage-ebs-test
      instance_type: t2.medium
  - name: es
    driver:
      tags:
        Name: storage-es-test
      instance_type: c3.xlarge
  - name: nvme
    driver:
      tags:
        Name: storage-nvme-test
      instance_type: i3.large
